Switch to Okta

diff --git a/docker-credential-adfs-ecr-login b/docker-credential-adfs-ecr-login
--- a/docker-credential-adfs-ecr-login
+++ b/docker-credential-adfs-ecr-login
@@ -8,12 +8,12 @@ PYENV_VERSION=genv aws sts get-caller-identity &> /dev/null
 exit_status=$?
 
 if [ $exit_status -ne 0 ]; then
-  >&2 echo "Error Logging in, attempting to refresh token with aws-adfs login"
-  PYENV_VERSION=genv username=${USER}@zefr.com password=`security find-generic-password -a ${USER} -s sso -w` aws-adfs login --env --adfs-host=sso.zefr.com --session-duration 43200 1>&2
+  >&2 echo "Error Logging in, attempting to refresh token with aws-okta"
+  aws-okta exec zefr -a12h -t12h -- aws-save-creds 1>&2
   exit_status=$?
 
   if [ $exit_status -ne 0 ]; then
-    >&2 echo "Error make sure latest password is in your keychain by running: 'security add-generic-password -a ${USER} -s sso -w'"
+    >&2 echo "Error logging in"
   fi
 fi
 
