Do not use helper for docker hub

diff --git a/docker-credential-adfs-ecr-login b/docker-credential-adfs-ecr-login
--- a/docker-credential-adfs-ecr-login
+++ b/docker-credential-adfs-ecr-login
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 if ! docker-credential-ecr-login $@; then
-  >&2 echo "Error Logging in, attempting to refresh token"
+  >&2 echo "Error Logging in, attempting to refresh token with aws-adfs login"
   PYENV_VERSION=genv username=$SSO_USER password=$SSO_PASS aws-adfs login --env --adfs-host=sso.zefr.com --session-duration 43200
 
   >&2 echo "Trying again..."
