docker-credential-ecr-login always exits 0
Change to another tool that should give a correct exit code when the token has expired.

diff --git a/docker-credential-adfs-ecr-login b/docker-credential-adfs-ecr-login
--- a/docker-credential-adfs-ecr-login
+++ b/docker-credential-adfs-ecr-login
@@ -3,18 +3,18 @@
 # Collect stdin from docker for passing multiple times
 cred_in=`cat`
 
-docker-credential-ecr-login $@ <<< "${cred_in}"
+# Check if the aws token is expired
+PYENV_VERSION=genv aws sts get-caller-identity &> /dev/null
 exit_status=$?
 
 if [ $exit_status -ne 0 ]; then
   >&2 echo "Error Logging in, attempting to refresh token with aws-adfs login"
   PYENV_VERSION=genv username=${USER}@zefr.com password=`security find-generic-password -a ${USER} -s sso -w` aws-adfs login --env --adfs-host=sso.zefr.com --session-duration 43200
-
-  >&2 echo "Trying again..."
-  docker-credential-ecr-login $@ <<< "${cred_in}"
   exit_status=$?
+
+  if [ $exit_status -ne 0 ]; then
+    >&2 echo "Error make sure latest password is in your keychain by running: 'security add-generic-password -a ${USER} -s sso -w'"
+  fi
 fi
 
-if [ $exit_status -ne 0 ]; then
-  >&2 echo "Error make sure latest password is in your keychain by running: 'security add-generic-password -a ${USER} -s sso -w'"
-fi
+docker-credential-ecr-login $@ <<< "${cred_in}"
