Add edited files that were sitting on local
I hope these are good changes

diff --git a/docker-credential-sso-ecr-login b/docker-credential-sso-ecr-login
--- a/docker-credential-sso-ecr-login
+++ b/docker-credential-sso-ecr-login
@@ -8,8 +8,8 @@ PYENV_VERSION=genv aws sts get-caller-identity &> /dev/null
 exit_status=$?
 
 if [ $exit_status -ne 0 ]; then
-  >&2 echo "Error Logging in, attempting to refresh token with aws-okta"
-  aws-okta exec zefr -a12h -t12h -- aws-save-creds 1>&2
+  >&2 echo "Logging in, attempting to refresh token, warning this will fail, just run a 2nd time ;)"
+  /usr/local/aws-cli/aws sso login --profile shared; aws2-wrap --profile shared --exec "aws-save-creds"
   exit_status=$?
 
   if [ $exit_status -ne 0 ]; then
