Working Auth, finally...

diff --git a/docker-credential-adfs-ecr-login b/docker-credential-adfs-ecr-login
--- a/docker-credential-adfs-ecr-login
+++ b/docker-credential-adfs-ecr-login
@@ -1,8 +1,20 @@
 #!/bin/bash
-if docker-credential-ecr-login $@; then
-  >&2 echo "Error Logging in, attempting to refresh token with aws-adfs login $?"
+
+# Collect stdin from docker for passing multiple times
+cred_in=`cat`
+
+echo "${cred_in}" | docker-credential-ecr-login $@
+exit_status=$?
+
+if [ $exit_status -ne 0 ]; then
+  >&2 echo "Error Logging in, attempting to refresh token with aws-adfs login"
   PYENV_VERSION=genv username=${USER}@zefr.com password=`security find-generic-password -a ${USER} -s sso -w` aws-adfs login --env --adfs-host=sso.zefr.com --session-duration 43200
 
   >&2 echo "Trying again..."
+  echo "${cred_in}" | docker-credential-ecr-login $@
+  exit_status=$?
 fi
-docker-credential-ecr-login $@
+
+if [ $exit_status -ne 0 ]; then
+  >&2 echo "Error make sure latest password is in your keychain by running: 'security add-generic-password -a ${USER} -s sso -w'"
+fi
