Add pre-commit support

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -1,41 +1,56 @@
 #!/bin/bash
 
-EXITS=()
-if [[ -f "pyproject.toml" ]]; then
-    black --check .
-    EXITS+=($?)
+# start templated
+INSTALL_PYTHON=/Users/kyle.walker/.pyenv/versions/3.10.4/envs/genv/bin/python3.10
+ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
+# end templated
 
-    flake8
-    EXITS+=($?)
-elif [[ -f "setup.py" || -f "requirements.txt" ]]; then
-    flake8
-    EXITS+=($?)
+HERE="$(cd "$(dirname "$0")" && pwd)"
+ARGS+=(--hook-dir "$HERE" -- "$@")
+
+if [ -x "$INSTALL_PYTHON" ]; then
+    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
+elif command -v pre-commit > /dev/null; then
+    exec pre-commit "${ARGS[@]}"
 else
-    # Unlikely a python project
-    EXITS+=(0)
-fi
+    EXITS=()
+    if [[ -f "pyproject.toml" ]]; then
+        black --check .
+        EXITS+=($?)
 
-# Set array expansion integer seperator to line breaks
-IFS=$'\n'
-# Get the largest exit code
-EXIT_CODE=`echo "${EXITS[*]}" | sort -nr | head -n1`
+        flake8
+        EXITS+=($?)
+    elif [[ -f "setup.py" || -f "requirements.txt" ]]; then
+        flake8
+        EXITS+=($?)
+    else
+        # Unlikely a python project
+        EXITS+=(0)
+    fi
 
-if [ $EXIT_CODE = 1 ]; then
-    read -p "You're about to commit with a linter error, continue? [y|n] " -n 1 -r < /dev/tty
-    echo
-    if echo $REPLY | grep -E '^[Yy]$' > /dev/null
-    then
+    # Set array expansion integer seperator to line breaks
+    IFS=$'\n'
+    # Get the largest exit code
+    EXIT_CODE=`echo "${EXITS[*]}" | sort -nr | head -n1`
+
+    if [ $EXIT_CODE = 1 ]; then
+        read -p "You're about to commit with a linter error, continue? [y|n] " -n 1 -r < /dev/tty
+        echo
+        if echo $REPLY | grep -E '^[Yy]$' > /dev/null
+        then
+            exit 0 # push will execute
+        fi
+        exit 1 # push will not execute
+    elif [ $EXIT_CODE = 127 ]; then
+        read -p "You're about to commit with without linter(s) found, continue? [y|n] " -n 1 -r < /dev/tty
+        echo
+        if echo $REPLY | grep -E '^[Yy]$' > /dev/null
+        then
+            exit 0 # push will execute
+        fi
+        exit 1 # push will not execute
+    else
         exit 0 # push will execute
     fi
-    exit 1 # push will not execute
-elif [ $EXIT_CODE = 127 ]; then
-    read -p "You're about to commit with without linter(s) found, continue? [y|n] " -n 1 -r < /dev/tty
-    echo
-    if echo $REPLY | grep -E '^[Yy]$' > /dev/null
-    then
-        exit 0 # push will execute
-    fi
-    exit 1 # push will not execute
-else
-    exit 0 # push will execute
+
 fi
